name: Test ElectronJS

on:
  push:
    branches:
      - develop

jobs:
  windows:
    runs-on: ubuntu-latest

    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: 💾 Validate cache
        run: npm ci

      - name: 🕵 Run ESLint
        run: npm run lint

      - name: 🕵 Run Jest test
        run: npm run jest
